########################### NETWORKS
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

########################### SERVICES
include:
  - compose/jellyfin.yml
  - compose/radarr.yml
  - compose/sonarr.yml
  - compose/bazarr.yml
  - compose/seerr.yml
  - compose/qbittorrent.yml
  - compose/jackett.yml
  - compose/flaresolverr.yml
  - compose/gluetun.yml