services:
  flaresolverr:
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
    container_name: flaresolverr
