services:
  # Radarr - Movies Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    networks:
      - default
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MEDIADIR:/media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ