services:
  # Sonarr - TV Shows Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    networks:
      - default
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/sonarr:/config
      - $MEDIADIR:/media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ